/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SugarRushPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/buffer-parser.ts
var import_obsidian2 = require("obsidian");

// src/logger.ts
var import_obsidian = require("obsidian");
var Logger = class {
  constructor(app, settings) {
    __publicField(this, "app");
    __publicField(this, "settings");
    __publicField(this, "logBuffer", []);
    __publicField(this, "isWriting", false);
    __publicField(this, "writePromise");
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  shouldLog(level) {
    return level >= this.settings.logLevel && this.settings.logLevel !== 6 /* OFF */;
  }
  formatTimestamp() {
    const now = new Date();
    switch (this.settings.timestampFormat) {
      case "iso":
        return now.toISOString();
      case "locale":
        return now.toLocaleString();
      case "unix":
        return now.getTime().toString();
      default:
        return now.toISOString();
    }
  }
  getLevelName(level) {
    switch (level) {
      case 0 /* TRACE */:
        return "TRACE";
      case 1 /* DEBUG */:
        return "DEBUG";
      case 2 /* INFO */:
        return "INFO";
      case 3 /* WARN */:
        return "WARN";
      case 4 /* ERROR */:
        return "ERROR";
      case 5 /* FATAL */:
        return "FATAL";
      default:
        return "UNKNOWN";
    }
  }
  createLogEntry(level, component, message, data, error) {
    return {
      timestamp: this.formatTimestamp(),
      level,
      component,
      message,
      data,
      error
    };
  }
  formatLogEntry(entry) {
    const levelName = this.getLevelName(entry.level).padEnd(5);
    const component = entry.component.padEnd(20);
    let logLine = `[${entry.timestamp}] ${levelName} ${component} | ${entry.message}`;
    if (entry.data) {
      logLine += `
  Data: ${JSON.stringify(entry.data, null, 2)}`;
    }
    if (entry.error) {
      logLine += `
  Error: ${entry.error.message}`;
      if (this.settings.includeStackTrace && entry.error.stack) {
        logLine += `
  Stack: ${entry.error.stack}`;
      }
    }
    return logLine;
  }
  async writeToConsole(entry) {
    if (!this.settings.enableConsoleLogging)
      return;
    const formattedMessage = this.formatLogEntry(entry);
    switch (entry.level) {
      case 0 /* TRACE */:
      case 1 /* DEBUG */:
        console.debug(formattedMessage);
        break;
      case 2 /* INFO */:
        console.info(formattedMessage);
        break;
      case 3 /* WARN */:
        console.warn(formattedMessage);
        break;
      case 4 /* ERROR */:
      case 5 /* FATAL */:
        console.error(formattedMessage);
        break;
    }
  }
  async writeToFile(entry) {
    if (!this.settings.enableFileLogging || !this.settings.logFilePath)
      return;
    const formattedMessage = this.formatLogEntry(entry) + "\n";
    try {
      let logFile = this.app.vault.getAbstractFileByPath(this.settings.logFilePath);
      if (!logFile) {
        await this.app.vault.create(this.settings.logFilePath, "");
        logFile = this.app.vault.getAbstractFileByPath(this.settings.logFilePath);
      }
      if (logFile instanceof import_obsidian.TFile) {
        await this.rotateLogFileIfNeeded(logFile);
        const currentContent = await this.app.vault.read(logFile);
        await this.app.vault.modify(logFile, currentContent + formattedMessage);
      }
    } catch (error) {
      console.error("Sugar Rush Logger: Failed to write to log file:", error);
      console.log("Log entry that failed to write:", formattedMessage);
    }
  }
  async rotateLogFileIfNeeded(logFile) {
    try {
      const content = await this.app.vault.read(logFile);
      const sizeInMB = new Blob([content]).size / (1024 * 1024);
      if (sizeInMB >= this.settings.maxLogFileSize) {
        await this.rotateLogFiles();
      }
    } catch (error) {
      console.error("Sugar Rush Logger: Failed to check log file size:", error);
    }
  }
  async rotateLogFiles() {
    try {
      const basePath = this.settings.logFilePath.replace(/\.[^/.]+$/, "");
      const extension = this.settings.logFilePath.split(".").pop() || "log";
      const oldestLogPath = `${basePath}.${this.settings.maxLogFiles}.${extension}`;
      const oldestLog = this.app.vault.getAbstractFileByPath(oldestLogPath);
      if (oldestLog instanceof import_obsidian.TFile) {
        await this.app.vault.delete(oldestLog);
      }
      for (let i = this.settings.maxLogFiles - 1; i >= 1; i--) {
        const currentPath = `${basePath}.${i}.${extension}`;
        const nextPath = `${basePath}.${i + 1}.${extension}`;
        const currentFile = this.app.vault.getAbstractFileByPath(currentPath);
        if (currentFile instanceof import_obsidian.TFile) {
          await this.app.fileManager.renameFile(currentFile, nextPath);
        }
      }
      const currentLog = this.app.vault.getAbstractFileByPath(this.settings.logFilePath);
      if (currentLog instanceof import_obsidian.TFile) {
        const firstRotatedPath = `${basePath}.1.${extension}`;
        await this.app.fileManager.renameFile(currentLog, firstRotatedPath);
      }
      await this.app.vault.create(this.settings.logFilePath, "");
    } catch (error) {
      console.error("Sugar Rush Logger: Failed to rotate log files:", error);
    }
  }
  async processLogBuffer() {
    if (this.isWriting || this.logBuffer.length === 0)
      return;
    this.isWriting = true;
    try {
      const entriesToProcess = [...this.logBuffer];
      this.logBuffer = [];
      for (const entry of entriesToProcess) {
        await Promise.all([
          this.writeToConsole(entry),
          this.writeToFile(entry)
        ]);
      }
    } catch (error) {
      console.error("Sugar Rush Logger: Error processing log buffer:", error);
    } finally {
      this.isWriting = false;
      if (this.logBuffer.length > 0) {
        setTimeout(() => this.processLogBuffer(), 0);
      }
    }
  }
  async log(level, component, message, data, error) {
    if (!this.shouldLog(level))
      return;
    const entry = this.createLogEntry(level, component, message, data, error);
    this.logBuffer.push(entry);
    if (!this.writePromise) {
      this.writePromise = this.processLogBuffer().finally(() => {
        this.writePromise = void 0;
      });
    }
    return this.writePromise;
  }
  // Public logging methods
  trace(component, message, data) {
    return this.log(0 /* TRACE */, component, message, data);
  }
  debug(component, message, data) {
    return this.log(1 /* DEBUG */, component, message, data);
  }
  info(component, message, data) {
    return this.log(2 /* INFO */, component, message, data);
  }
  warn(component, message, data, error) {
    return this.log(3 /* WARN */, component, message, data, error);
  }
  error(component, message, data, error) {
    return this.log(4 /* ERROR */, component, message, data, error);
  }
  fatal(component, message, data, error) {
    return this.log(5 /* FATAL */, component, message, data, error);
  }
  // Utility methods
  async flush() {
    if (this.writePromise) {
      await this.writePromise;
    }
  }
  async clearLogFile() {
    try {
      const logFile = this.app.vault.getAbstractFileByPath(this.settings.logFilePath);
      if (logFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(logFile, "");
        new import_obsidian.Notice("Sugar Rush: Log file cleared");
      }
    } catch (error) {
      console.error("Sugar Rush Logger: Failed to clear log file:", error);
      new import_obsidian.Notice("Sugar Rush: Failed to clear log file");
    }
  }
  async getLogFileContent() {
    try {
      const logFile = this.app.vault.getAbstractFileByPath(this.settings.logFilePath);
      if (logFile instanceof import_obsidian.TFile) {
        return await this.app.vault.read(logFile);
      }
      return "";
    } catch (error) {
      console.error("Sugar Rush Logger: Failed to read log file:", error);
      return "";
    }
  }
  async getLogFileSize() {
    try {
      const content = await this.getLogFileContent();
      return new Blob([content]).size;
    } catch (error) {
      console.error("Sugar Rush Logger: Failed to get log file size:", error);
      return 0;
    }
  }
};
function createComponentLogger(logger, componentName) {
  return {
    trace: (message, data) => logger.trace(componentName, message, data),
    debug: (message, data) => logger.debug(componentName, message, data),
    info: (message, data) => logger.info(componentName, message, data),
    warn: (message, data, error) => logger.warn(componentName, message, data, error),
    error: (message, data, error) => logger.error(componentName, message, data, error),
    fatal: (message, data, error) => logger.fatal(componentName, message, data, error)
  };
}

// src/buffer-parser.ts
var BufferParser = class {
  constructor(logger) {
    __publicField(this, "log");
    if (logger) {
      this.log = createComponentLogger(logger, "BufferParser");
    }
  }
  /**
   * Parses directory buffer content and returns file operations to execute
   */
  parseFileOperations(originalContent, editedContent, basePath) {
    var _a, _b;
    (_a = this.log) == null ? void 0 : _a.debug("Parsing file operations", { basePath, originalLineCount: originalContent.split("\n").length, editedLineCount: editedContent.split("\n").length });
    const originalLines = this.parseDirectoryLines(originalContent, basePath);
    const editedLines = this.parseDirectoryLines(editedContent, basePath);
    const operations = [];
    const originalMap = new Map(originalLines.map((line) => [line.lineNumber, line]));
    const editedMap = new Map(editedLines.map((line) => [line.lineNumber, line]));
    for (const [lineNum, originalLine] of originalMap) {
      if (!editedMap.has(lineNum) && originalLine.name !== "..") {
        operations.push({
          type: "delete",
          path: originalLine.path
        });
      }
    }
    for (const [lineNum, editedLine] of editedMap) {
      const originalLine = originalMap.get(lineNum);
      if (originalLine) {
        if (originalLine.name !== editedLine.name && editedLine.name !== "..") {
          const newPath = this.constructNewPath(basePath, editedLine.name, originalLine.isFolder);
          operations.push({
            type: "rename",
            path: newPath,
            oldPath: originalLine.path,
            newPath,
            newName: editedLine.name
          });
        }
      } else {
        if (editedLine.name !== ".." && editedLine.name.trim() !== "") {
          const newPath = this.constructNewPath(basePath, editedLine.name, editedLine.isFolder);
          operations.push({
            type: "create",
            path: newPath,
            newName: editedLine.name
          });
        }
      }
    }
    (_b = this.log) == null ? void 0 : _b.info("Parsed file operations", { operationCount: operations.length, operations: operations.map((op) => ({ type: op.type, path: op.path })) });
    return operations;
  }
  /**
   * Parses directory content into structured line data
   */
  parseDirectoryLines(content, basePath) {
    const lines = content.split("\n").filter((line) => line.trim() !== "");
    const directoryLines = [];
    lines.forEach((line, index) => {
      const parsed = this.parseDirectoryLine(line, index, basePath);
      if (parsed) {
        directoryLines.push(parsed);
      }
    });
    return directoryLines;
  }
  /**
   * Parses a single line of directory content
   */
  parseDirectoryLine(line, lineNumber, basePath) {
    const match = line.match(/^(\s*)([📁📄])\s+(.+)$/);
    if (!match)
      return null;
    const [, indent, icon, name] = match;
    const depth = Math.floor((indent || "").length / 2);
    const isFolder = icon === "\u{1F4C1}";
    const path = name === ".." ? this.getParentPath(basePath) : this.constructPath(basePath, name || "");
    return {
      path,
      name: name || "",
      isFolder,
      depth,
      lineNumber,
      existsInOriginal: true
    };
  }
  /**
   * Constructs full path for a file/folder
   */
  constructPath(basePath, name) {
    if (basePath === "/" || basePath === "") {
      return name;
    }
    return `${basePath}/${name}`;
  }
  /**
   * Constructs new path after rename/create operations
   */
  constructNewPath(basePath, name, isFolder) {
    let cleanName = name.trim();
    if (!isFolder && !cleanName.includes(".")) {
      cleanName += ".md";
    }
    return this.constructPath(basePath, cleanName);
  }
  /**
   * Gets parent directory path
   */
  getParentPath(path) {
    if (path === "/" || path === "")
      return "/";
    const segments = path.split("/").filter((s) => s !== "");
    return segments.length > 1 ? "/" + segments.slice(0, -1).join("/") : "/";
  }
  /**
   * Validates file operations before execution
   */
  validateOperations(operations) {
    const errors = [];
    for (const op of operations) {
      switch (op.type) {
        case "rename":
          if (!op.oldPath || !op.newPath) {
            errors.push(`Invalid rename operation: missing paths`);
          }
          if (op.newName && !this.isValidFileName(op.newName)) {
            errors.push(`Invalid filename: ${op.newName}`);
          }
          break;
        case "create":
          if (!op.path || !op.newName) {
            errors.push(`Invalid create operation: missing path or name`);
          }
          if (op.newName && !this.isValidFileName(op.newName)) {
            errors.push(`Invalid filename: ${op.newName}`);
          }
          break;
        case "delete":
          if (!op.path) {
            errors.push(`Invalid delete operation: missing path`);
          }
          break;
      }
    }
    return {
      valid: errors.length === 0,
      errors
    };
  }
  /**
   * Validates filename according to filesystem rules
   */
  isValidFileName(name) {
    if (!name || name.trim() === "")
      return false;
    const invalidChars = /[<>:"/\\|?*\x00-\x1f]/;
    if (invalidChars.test(name))
      return false;
    const reservedNames = /^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\.|$)/i;
    if (reservedNames.test(name))
      return false;
    if (name.length > 255)
      return false;
    return true;
  }
  /**
   * Formats directory contents as editable buffer text
   */
  formatDirectoryAsBuffer(files, showExtensions = true) {
    return files.map((file) => {
      const icon = file instanceof import_obsidian2.TFolder ? "\u{1F4C1}" : "\u{1F4C4}";
      let name = file.name;
      if (name === "..") {
        return `\u{1F4C1} ..`;
      }
      if (!showExtensions && file instanceof import_obsidian2.TFile) {
        const lastDot = name.lastIndexOf(".");
        if (lastDot > 0) {
          name = name.substring(0, lastDot);
        }
      }
      return `${icon} ${name}`;
    }).join("\n");
  }
  /**
   * Extracts file information from a buffer line
   */
  extractFileFromLine(line) {
    const match = line.match(/^[📁📄]\s+(.+)$/);
    if (!match)
      return null;
    const name = match[1] || "";
    const isFolder = line.startsWith("\u{1F4C1}");
    return { name, isFolder };
  }
};

// src/file-operations-manager.ts
var import_obsidian3 = require("obsidian");
var FileOperationsManager = class {
  constructor(app, maxUndoHistory = 50, logger) {
    __publicField(this, "app");
    __publicField(this, "undoHistory", []);
    __publicField(this, "maxUndoHistory", 50);
    __publicField(this, "log");
    this.app = app;
    this.maxUndoHistory = maxUndoHistory;
    if (logger) {
      this.log = createComponentLogger(logger, "FileOperationsManager");
    }
  }
  /**
   * Executes a batch of file operations
   */
  async executeFileOperations(operations) {
    var _a, _b;
    if (operations.length === 0) {
      (_a = this.log) == null ? void 0 : _a.debug("No operations to execute");
      return [];
    }
    (_b = this.log) == null ? void 0 : _b.info("Executing file operations", { operationCount: operations.length });
    const results = [];
    const batches = this.groupOperationsByType(operations);
    this.addToUndoHistory(operations);
    try {
      for (const batch of batches) {
        const batchResults = await this.executeBatch(batch);
        results.push(...batchResults);
      }
      await this.updateMetadataCache();
      if (results.every((r) => r.success)) {
        new import_obsidian3.Notice(`Successfully executed ${operations.length} file operation(s)`);
      } else {
        const failed = results.filter((r) => !r.success).length;
        new import_obsidian3.Notice(`Completed with ${failed} error(s). Check console for details.`);
      }
    } catch (error) {
      console.error("Sugar Rush: Failed to execute file operations:", error);
      new import_obsidian3.Notice("Failed to execute file operations");
    }
    return results;
  }
  /**
   * Groups operations by type for batch processing
   */
  groupOperationsByType(operations) {
    const batches = /* @__PURE__ */ new Map();
    const order = ["create", "rename", "move", "delete"];
    for (const type of order) {
      batches.set(type, operations.filter((op) => op.type === type));
    }
    return Array.from(batches.entries()).filter(([_, ops]) => ops.length > 0).map(([type, ops]) => ({ type, operations: ops }));
  }
  /**
   * Executes a single batch of operations
   */
  async executeBatch(batch) {
    const results = [];
    for (const operation of batch.operations) {
      try {
        const result = await this.executeOperation(operation);
        results.push(result);
        if (!result.success) {
          console.error(`Sugar Rush: Operation failed:`, result.error);
        }
      } catch (error) {
        results.push({
          success: false,
          operation,
          error: error instanceof Error ? error.message : "Unknown error"
        });
      }
    }
    return results;
  }
  /**
   * Executes a single file operation
   */
  async executeOperation(operation) {
    switch (operation.type) {
      case "create":
        return await this.executeCreate(operation);
      case "rename":
        return await this.executeRename(operation);
      case "move":
        return await this.executeMove(operation);
      case "delete":
        return await this.executeDelete(operation);
      default:
        return {
          success: false,
          operation,
          error: `Unknown operation type: ${operation.type}`
        };
    }
  }
  /**
   * Creates a new file or folder
   */
  async executeCreate(operation) {
    if (!operation.path || !operation.newName) {
      return {
        success: false,
        operation,
        error: "Missing path or name for create operation"
      };
    }
    try {
      const existing = this.app.vault.getAbstractFileByPath(operation.path);
      if (existing) {
        return {
          success: false,
          operation,
          error: `File already exists: ${operation.path}`
        };
      }
      const isFolder = !operation.newName.includes(".") || operation.newName.endsWith("/");
      if (isFolder) {
        await this.app.vault.createFolder(operation.path);
      } else {
        const content = operation.newName.endsWith(".md") ? "" : "";
        await this.app.vault.create(operation.path, content);
      }
      return {
        success: true,
        operation
      };
    } catch (error) {
      return {
        success: false,
        operation,
        error: error instanceof Error ? error.message : "Failed to create file"
      };
    }
  }
  /**
   * Renames a file or folder
   */
  async executeRename(operation) {
    if (!operation.oldPath || !operation.newPath) {
      return {
        success: false,
        operation,
        error: "Missing paths for rename operation"
      };
    }
    try {
      const file = this.app.vault.getAbstractFileByPath(operation.oldPath);
      if (!file) {
        return {
          success: false,
          operation,
          error: `File not found: ${operation.oldPath}`
        };
      }
      const existing = this.app.vault.getAbstractFileByPath(operation.newPath);
      if (existing) {
        return {
          success: false,
          operation,
          error: `Target already exists: ${operation.newPath}`
        };
      }
      await this.app.fileManager.renameFile(file, operation.newPath);
      return {
        success: true,
        operation
      };
    } catch (error) {
      return {
        success: false,
        operation,
        error: error instanceof Error ? error.message : "Failed to rename file"
      };
    }
  }
  /**
   * Moves a file or folder to a different directory
   */
  async executeMove(operation) {
    if (!operation.oldPath || !operation.targetDirectory) {
      return {
        success: false,
        operation,
        error: "Missing paths for move operation"
      };
    }
    try {
      const file = this.app.vault.getAbstractFileByPath(operation.oldPath);
      if (!file) {
        return {
          success: false,
          operation,
          error: `File not found: ${operation.oldPath}`
        };
      }
      const targetDir = this.app.vault.getAbstractFileByPath(operation.targetDirectory);
      if (!targetDir || !(targetDir instanceof import_obsidian3.TFolder)) {
        return {
          success: false,
          operation,
          error: `Target directory not found: ${operation.targetDirectory}`
        };
      }
      const newPath = `${operation.targetDirectory}/${file.name}`;
      const existing = this.app.vault.getAbstractFileByPath(newPath);
      if (existing) {
        return {
          success: false,
          operation,
          error: `Target already exists: ${newPath}`
        };
      }
      await this.app.fileManager.renameFile(file, newPath);
      return {
        success: true,
        operation
      };
    } catch (error) {
      return {
        success: false,
        operation,
        error: error instanceof Error ? error.message : "Failed to move file"
      };
    }
  }
  /**
   * Deletes a file or folder
   */
  async executeDelete(operation) {
    if (!operation.path) {
      return {
        success: false,
        operation,
        error: "Missing path for delete operation"
      };
    }
    try {
      const file = this.app.vault.getAbstractFileByPath(operation.path);
      if (!file) {
        return {
          success: false,
          operation,
          error: `File not found: ${operation.path}`
        };
      }
      await this.app.vault.trash(file, false);
      return {
        success: true,
        operation
      };
    } catch (error) {
      return {
        success: false,
        operation,
        error: error instanceof Error ? error.message : "Failed to delete file"
      };
    }
  }
  /**
   * Updates Obsidian's metadata cache after operations
   */
  async updateMetadataCache() {
    try {
      this.app.metadataCache.trigger("resolved");
      await new Promise((resolve) => setTimeout(resolve, 100));
    } catch (error) {
      console.warn("Sugar Rush: Failed to update metadata cache:", error);
    }
  }
  /**
   * Adds operations to undo history
   */
  addToUndoHistory(operations) {
    this.undoHistory.push([...operations]);
    if (this.undoHistory.length > this.maxUndoHistory) {
      this.undoHistory.shift();
    }
  }
  /**
   * Gets the last set of operations for undo
   */
  getLastOperations() {
    return this.undoHistory.length > 0 ? this.undoHistory[this.undoHistory.length - 1] || null : null;
  }
  /**
   * Attempts to undo the last set of operations
   */
  async undoLastOperations() {
    const lastOps = this.undoHistory.pop();
    if (!lastOps)
      return false;
    try {
      const reverseOps = this.createReverseOperations(lastOps);
      const results = await this.executeOperationsWithoutUndo(reverseOps);
      const success = results.every((r) => r.success);
      if (success) {
        new import_obsidian3.Notice("Successfully undid file operations");
      } else {
        new import_obsidian3.Notice("Failed to undo some operations");
        this.undoHistory.push(lastOps);
      }
      return success;
    } catch (error) {
      console.error("Sugar Rush: Failed to undo operations:", error);
      this.undoHistory.push(lastOps);
      return false;
    }
  }
  /**
   * Creates reverse operations for undo functionality
   */
  createReverseOperations(operations) {
    const reverseOps = [];
    for (let i = operations.length - 1; i >= 0; i--) {
      const op = operations[i];
      if (!op)
        continue;
      switch (op.type) {
        case "create":
          reverseOps.push({
            type: "delete",
            path: op.path
          });
          break;
        case "rename":
          if (op.newPath && op.oldPath) {
            reverseOps.push({
              type: "rename",
              path: op.oldPath,
              oldPath: op.newPath,
              newPath: op.oldPath
            });
          }
          break;
        case "delete":
          break;
        case "move":
          if (op.oldPath && op.targetDirectory) {
            const fileName = op.oldPath.split("/").pop();
            if (fileName) {
              const originalDir = op.oldPath.replace("/" + fileName, "");
              reverseOps.push({
                type: "move",
                path: op.oldPath,
                oldPath: `${op.targetDirectory}/${fileName}`,
                targetDirectory: originalDir
              });
            }
          }
          break;
      }
    }
    return reverseOps;
  }
  /**
   * Executes operations without adding to undo history
   */
  async executeOperationsWithoutUndo(operations) {
    const results = [];
    for (const operation of operations) {
      try {
        const result = await this.executeOperation(operation);
        results.push(result);
      } catch (error) {
        results.push({
          success: false,
          operation,
          error: error instanceof Error ? error.message : "Unknown error"
        });
      }
    }
    return results;
  }
  /**
   * Clears undo history
   */
  clearUndoHistory() {
    this.undoHistory = [];
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  enableMinusKeyNavigation: true,
  enableContinuousNavigation: true,
  returnToFileHotkey: "Ctrl+^",
  showFileExtensions: true,
  showHiddenFiles: false,
  indentationStyle: "spaces",
  indentationSize: 2,
  enableCustomVimCommands: true,
  customKeybindings: {},
  lazyLoadThreshold: 1e3,
  debounceDelay: 500,
  confirmDeletions: true,
  enableUndo: true,
  maxUndoHistory: 50,
  logging: {
    logLevel: 2 /* INFO */,
    enableConsoleLogging: true,
    enableFileLogging: false,
    logFilePath: "sugar-rush.log",
    maxLogFileSize: 10,
    // 10MB
    maxLogFiles: 5,
    includeStackTrace: true,
    timestampFormat: "iso"
  }
};
var NavigationEngine = class {
  constructor(app, plugin) {
    __publicField(this, "app");
    __publicField(this, "plugin");
    __publicField(this, "previousViewState", null);
    __publicField(this, "log");
    this.app = app;
    this.plugin = plugin;
    this.log = createComponentLogger(plugin.logger, "NavigationEngine");
  }
  async handleMinusKey(evt) {
    var _a;
    this.log.trace("Handle minus key pressed");
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!activeView) {
      this.log.debug("No active markdown view found");
      return false;
    }
    if (!this.isInNormalMode(activeView)) {
      this.log.debug("Not in vim normal mode, ignoring minus key");
      return false;
    }
    this.previousViewState = {
      file: activeView.file,
      cursor: activeView.editor.getCursor(),
      scrollTop: activeView.editor.getScrollInfo().top
    };
    const file = activeView.file;
    if (!file) {
      this.log.warn("No file in active view");
      return false;
    }
    const parentPath = ((_a = file.parent) == null ? void 0 : _a.path) || "/";
    this.log.info("Navigating to parent directory", { currentFile: file.path, parentPath });
    await this.showDirectoryInPane(parentPath, activeView.leaf);
    return true;
  }
  isInNormalMode(view) {
    var _a, _b;
    const vimMode = (_a = this.app.vault.config) == null ? void 0 : _a.vimMode;
    if (!vimMode)
      return true;
    const cm = view.editor.cm;
    if (!cm || !((_b = cm.state) == null ? void 0 : _b.vim))
      return true;
    return cm.state.vim.mode === "normal";
  }
  async showDirectoryInPane(path, leaf) {
    try {
      this.log.debug("Setting view state for directory", { path });
      await leaf.setViewState({
        type: "directory-edit",
        state: { path }
      });
      this.log.info("Successfully opened directory view", { path });
    } catch (error) {
      this.log.error("Failed to show directory view", { path }, error);
      new import_obsidian4.Notice("Failed to open directory view");
    }
  }
  async returnToPreviousFile() {
    if (!this.previousViewState) {
      this.log.debug("No previous view state to return to");
      return;
    }
    const { file, cursor, scrollTop } = this.previousViewState;
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf) {
      this.log.warn("No active leaf to return to previous file");
      return;
    }
    try {
      this.log.info("Returning to previous file", { filePath: file == null ? void 0 : file.path });
      await leaf.openFile(file);
      setTimeout(() => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
        if (view) {
          view.editor.setCursor(cursor);
          view.editor.scrollTo(null, scrollTop);
          this.log.debug("Restored cursor and scroll position", { cursor, scrollTop });
        }
      }, 50);
      this.previousViewState = null;
      this.log.info("Successfully returned to previous file");
    } catch (error) {
      this.log.error("Failed to return to previous file", { filePath: file == null ? void 0 : file.path }, error);
      new import_obsidian4.Notice("Failed to return to previous file");
    }
  }
};
var DirectoryEditView = class extends import_obsidian4.TextFileView {
  constructor(leaf, app, navigationEngine, plugin) {
    super(leaf);
    __publicField(this, "directoryPath", "");
    __publicField(this, "originalContent", "");
    __publicField(this, "navigationEngine");
    __publicField(this, "isLoading", false);
    __publicField(this, "bufferParser");
    __publicField(this, "fileOperationsManager");
    __publicField(this, "plugin");
    __publicField(this, "debouncedSave");
    __publicField(this, "hasUnsavedChanges", false);
    __publicField(this, "content", "");
    __publicField(this, "log");
    this.navigation = false;
    this.navigationEngine = navigationEngine;
    this.plugin = plugin;
    this.log = createComponentLogger(plugin.logger, "DirectoryEditView");
    this.bufferParser = new BufferParser(plugin.logger);
    this.fileOperationsManager = new FileOperationsManager(app, plugin.settings.maxUndoHistory, plugin.logger);
    this.debouncedSave = (0, import_obsidian4.debounce)(async () => {
      await this.executePendingOperations();
    }, plugin.settings.debounceDelay);
    this.log.debug("DirectoryEditView created");
  }
  getViewType() {
    return "directory-edit";
  }
  getDisplayText() {
    return this.directoryPath || "Directory";
  }
  getIcon() {
    return "folder";
  }
  async onLoadFile(file) {
  }
  getViewData() {
    return this.content;
  }
  setViewData(data, clear) {
    this.content = data;
  }
  clear() {
    this.content = "";
  }
  async onOpen() {
    this.log.debug("DirectoryEditView opening");
    await super.onOpen();
    let attempts = 0;
    const maxAttempts = 5;
    let state = this.leaf.getViewState().state;
    while (!(state == null ? void 0 : state.path) && attempts < maxAttempts) {
      const delay = Math.pow(2, attempts) * 10;
      this.log.debug("View state not ready, retrying...", { attempt: attempts + 1, delay });
      await new Promise((resolve) => setTimeout(resolve, delay));
      state = this.leaf.getViewState().state;
      attempts++;
    }
    if (state == null ? void 0 : state.path) {
      this.directoryPath = state.path;
      this.log.info("Loading directory contents", { path: this.directoryPath, attempts });
      await this.loadDirectoryContents();
    } else {
      this.log.warn("No directory path provided in view state after retries", { attempts });
    }
  }
  async onClose() {
    this.log.debug("DirectoryEditView closing");
    await super.onClose();
  }
  async loadDirectoryContents() {
    if (this.isLoading)
      return;
    this.isLoading = true;
    try {
      const files = await this.getDirectoryFiles(this.directoryPath);
      const content = this.bufferParser.formatDirectoryAsBuffer(files, this.plugin.settings.showFileExtensions);
      this.originalContent = content;
      this.setViewData(content, false);
      this.hasUnsavedChanges = false;
      this.enableVimModeIfNeeded();
      this.setupChangeMonitoring();
    } catch (error) {
      console.error("Sugar Rush: Failed to load directory contents:", error);
      this.setViewData("Error loading directory contents", false);
    } finally {
      this.isLoading = false;
    }
  }
  async getDirectoryFiles(path) {
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!folder || !(folder instanceof import_obsidian4.TFolder)) {
      throw new Error(`Path is not a directory: ${path}`);
    }
    const files = [];
    if (folder.parent) {
      const parentMarker = {
        name: "..",
        path: folder.parent.path,
        parent: folder.parent.parent,
        vault: folder.vault,
        children: [],
        isRoot: () => false
      };
      files.push(parentMarker);
    }
    const children = folder.children.slice();
    children.sort((a, b) => {
      if (a instanceof import_obsidian4.TFolder && b instanceof import_obsidian4.TFile)
        return -1;
      if (a instanceof import_obsidian4.TFile && b instanceof import_obsidian4.TFolder)
        return 1;
      return a.name.localeCompare(b.name);
    });
    children.forEach((child) => {
      if (child instanceof import_obsidian4.TFile || child instanceof import_obsidian4.TFolder) {
        files.push(child);
      }
    });
    return files;
  }
  setupChangeMonitoring() {
    const editor = this.editor;
    if (!editor)
      return;
    editor.on("change", () => {
      this.hasUnsavedChanges = true;
      this.debouncedSave();
    });
  }
  async executePendingOperations() {
    if (!this.hasUnsavedChanges)
      return;
    try {
      const currentContent = this.getViewData();
      const operations = this.bufferParser.parseFileOperations(
        this.originalContent,
        currentContent,
        this.directoryPath
      );
      if (operations.length === 0) {
        this.hasUnsavedChanges = false;
        return;
      }
      const validation = this.bufferParser.validateOperations(operations);
      if (!validation.valid) {
        new import_obsidian4.Notice(`Invalid operations: ${validation.errors.join(", ")}`);
        return;
      }
      const results = await this.fileOperationsManager.executeFileOperations(operations);
      const allSuccessful = results.every((r) => r.success);
      if (allSuccessful) {
        this.hasUnsavedChanges = false;
        await this.loadDirectoryContents();
      } else {
        const errors = results.filter((r) => !r.success).map((r) => r.error);
        new import_obsidian4.Notice(`Some operations failed: ${errors.join(", ")}`);
      }
    } catch (error) {
      console.error("Sugar Rush: Failed to execute pending operations:", error);
      new import_obsidian4.Notice("Failed to execute file operations");
    }
  }
  enableVimModeIfNeeded() {
    var _a;
    const vimMode = (_a = this.app.vault.config) == null ? void 0 : _a.vimMode;
    if (!vimMode)
      return;
    const editor = this.editor;
    if (!(editor == null ? void 0 : editor.cm))
      return;
    try {
      const cm = editor.cm;
      cm.setOption("keyMap", "vim");
      this.setupDirectoryKeybindings(cm);
    } catch (error) {
      console.error("Sugar Rush: Failed to enable vim mode:", error);
    }
  }
  setupDirectoryKeybindings(cm) {
    const CM = globalThis.CodeMirror;
    if (typeof CM !== "undefined" && CM.Vim) {
      CM.Vim.defineAction("openFileOrFolder", (cm2) => {
        const cursor = cm2.getCursor();
        const line = cm2.getLine(cursor.line);
        this.handleFileOpen(line, cursor);
      });
      CM.Vim.map("<CR>", ":openFileOrFolder<CR>", "normal");
      CM.Vim.defineAction("navigateUp", (cm2) => {
        this.navigateToParent();
      });
      CM.Vim.map("-", ":navigateUp<CR>", "normal");
      CM.Vim.defineAction("appendNewFile", (cm2) => {
        const cursor = cm2.getCursor();
        const newLine = cursor.line + 1;
        cm2.replaceRange("\n\u{1F4C4} ", { line: cursor.line, ch: cm2.getLine(cursor.line).length });
        cm2.setCursor({ line: newLine, ch: 3 });
        CM.Vim.enterInsertMode(cm2);
      });
      CM.Vim.defineAction("insertNewFile", (cm2) => {
        const cursor = cm2.getCursor();
        cm2.replaceRange("\u{1F4C4} ", cursor);
        cm2.setCursor({ line: cursor.line, ch: cursor.ch + 3 });
        CM.Vim.enterInsertMode(cm2);
      });
      CM.Vim.map("a", ":appendNewFile<CR>", "normal");
      CM.Vim.map("i", ":insertNewFile<CR>", "normal");
      CM.Vim.defineAction("saveDirectory", (cm2) => {
        this.executePendingOperations();
      });
      CM.Vim.map(":w", ":saveDirectory<CR>", "normal");
      CM.Vim.defineAction("undoOperations", (cm2) => {
        this.undoLastOperations();
      });
      CM.Vim.map("u", ":undoOperations<CR>", "normal");
      if (this.plugin.settings.enableCustomVimCommands) {
        CM.Vim.defineEx("mkdir", "mkdir", (cm2, input) => {
          const dirName = input.args.join(" ");
          if (dirName) {
            this.createDirectory(dirName);
          }
        });
        CM.Vim.defineEx("touch", "touch", (cm2, input) => {
          const fileName = input.args.join(" ");
          if (fileName) {
            this.createFile(fileName);
          }
        });
        CM.Vim.defineEx("rename", "ren", (cm2, input) => {
          const newName = input.args.join(" ");
          if (newName) {
            this.renameCurrentFile(newName, cm2);
          }
        });
      }
    }
  }
  async handleFileOpen(line, cursor) {
    const fileName = this.extractFileNameFromLine(line);
    if (!fileName)
      return;
    if (fileName === "..") {
      await this.navigateToParent();
      return;
    }
    const filePath = this.directoryPath === "/" ? fileName : `${this.directoryPath}/${fileName}`;
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!file)
      return;
    if (file instanceof import_obsidian4.TFolder) {
      this.directoryPath = file.path;
      await this.loadDirectoryContents();
    } else if (file instanceof import_obsidian4.TFile) {
      await this.leaf.openFile(file);
    }
  }
  async navigateToParent() {
    const folder = this.app.vault.getAbstractFileByPath(this.directoryPath);
    if (folder && folder.parent) {
      this.directoryPath = folder.parent.path;
      await this.loadDirectoryContents();
    }
  }
  extractFileNameFromLine(line) {
    const fileInfo = this.bufferParser.extractFileFromLine(line);
    return fileInfo ? fileInfo.name : null;
  }
  async createDirectory(name) {
    const editor = this.editor;
    if (!editor)
      return;
    const cursor = editor.getCursor();
    const newLine = `\u{1F4C1} ${name}`;
    editor.replaceRange("\n" + newLine, { line: cursor.line, ch: editor.getLine(cursor.line).length });
    this.hasUnsavedChanges = true;
    this.debouncedSave();
  }
  async createFile(name) {
    const editor = this.editor;
    if (!editor)
      return;
    const cursor = editor.getCursor();
    const newLine = `\u{1F4C4} ${name}`;
    editor.replaceRange("\n" + newLine, { line: cursor.line, ch: editor.getLine(cursor.line).length });
    this.hasUnsavedChanges = true;
    this.debouncedSave();
  }
  async renameCurrentFile(newName, cm) {
    const cursor = cm.getCursor();
    const line = cm.getLine(cursor.line);
    const fileInfo = this.bufferParser.extractFileFromLine(line);
    if (fileInfo) {
      const icon = fileInfo.isFolder ? "\u{1F4C1}" : "\u{1F4C4}";
      const newLine = `${icon} ${newName}`;
      cm.replaceRange(newLine, { line: cursor.line, ch: 0 }, { line: cursor.line, ch: line.length });
      this.hasUnsavedChanges = true;
      this.debouncedSave();
    }
  }
  async undoLastOperations() {
    await this.fileOperationsManager.undoLastOperations();
    await this.loadDirectoryContents();
  }
  async save() {
    await this.executePendingOperations();
  }
};
var SugarRushPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    __publicField(this, "settings");
    __publicField(this, "navigationEngine");
    __publicField(this, "logger");
    __publicField(this, "log");
  }
  async onload() {
    console.log("Sugar Rush: onload() started");
    await this.loadSettings();
    console.log("Sugar Rush: Settings loaded:", this.settings);
    this.logger = new Logger(this.app, this.settings.logging);
    this.log = createComponentLogger(this.logger, "Plugin");
    console.log("Sugar Rush: Logger initialized");
    this.log.info("Sugar Rush plugin loading...");
    this.navigationEngine = new NavigationEngine(this.app, this);
    this.registerView(
      "directory-edit",
      (leaf) => new DirectoryEditView(leaf, this.app, this.navigationEngine, this)
    );
    this.addCommand({
      id: "navigate-parent",
      name: "Navigate to parent directory",
      hotkeys: [{ modifiers: [], key: "-" }],
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
        if (checking)
          return !!view && this.settings.enableMinusKeyNavigation;
        if (view && this.settings.enableMinusKeyNavigation) {
          this.navigationEngine.handleMinusKey(new Event("keydown"));
        }
        return true;
      }
    });
    this.addCommand({
      id: "return-to-file",
      name: "Return to previous file",
      hotkeys: [{ modifiers: ["Ctrl"], key: "^" }],
      callback: () => {
        this.navigationEngine.returnToPreviousFile();
      }
    });
    this.registerDomEvent(globalThis.document, "keydown", (evt) => {
      const keyEvent = evt;
      if (keyEvent.key === "-" && !keyEvent.ctrlKey && !keyEvent.altKey && !keyEvent.shiftKey && !keyEvent.metaKey) {
        const activeView = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
        if (activeView && this.settings.enableMinusKeyNavigation) {
          this.navigationEngine.handleMinusKey(evt).then((handled) => {
            if (handled) {
              keyEvent.preventDefault();
              keyEvent.stopPropagation();
            }
          });
        }
      }
    });
    console.log("Sugar Rush: Creating settings tab");
    const settingsTab = new SugarRushSettingTab(this.app, this);
    console.log("Sugar Rush: Settings tab created:", settingsTab);
    this.addSettingTab(settingsTab);
    console.log("Sugar Rush: Settings tab added to plugin");
    this.log.info("Sugar Rush plugin loaded successfully");
  }
  async onunload() {
    var _a, _b;
    (_a = this.log) == null ? void 0 : _a.info("Sugar Rush plugin unloading...");
    if (this.logger) {
      await this.logger.flush();
    }
    (_b = this.log) == null ? void 0 : _b.info("Sugar Rush plugin unloaded");
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
    if (loadedData == null ? void 0 : loadedData.logging) {
      this.settings.logging = Object.assign({}, DEFAULT_SETTINGS.logging, loadedData.logging);
    }
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    if (this.logger) {
      this.logger.updateSettings(this.settings.logging);
      (_a = this.log) == null ? void 0 : _a.debug("Logger settings updated");
    }
  }
};
var SugarRushSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    var _a, _b, _c;
    console.log("Sugar Rush: Settings display() method called");
    const { containerEl } = this;
    containerEl.empty();
    console.log("Sugar Rush: Container element cleared, creating header");
    containerEl.createEl("h2", { text: "Sugar Rush Settings" });
    console.log("Sugar Rush: Header created, plugin settings:", this.plugin.settings);
    containerEl.createEl("h3", { text: "Navigation" });
    new import_obsidian4.Setting(containerEl).setName("Enable minus key navigation").setDesc("Press - to navigate to parent directory").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMinusKeyNavigation).onChange(async (value) => {
      this.plugin.settings.enableMinusKeyNavigation = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Enable continuous navigation").setDesc("Allow repeated minus key presses to traverse up multiple levels").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableContinuousNavigation).onChange(async (value) => {
      this.plugin.settings.enableContinuousNavigation = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Display" });
    new import_obsidian4.Setting(containerEl).setName("Show file extensions").setDesc("Display file extensions in directory views").addToggle((toggle) => toggle.setValue(this.plugin.settings.showFileExtensions).onChange(async (value) => {
      this.plugin.settings.showFileExtensions = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Show hidden files").setDesc("Display hidden files and folders").addToggle((toggle) => toggle.setValue(this.plugin.settings.showHiddenFiles).onChange(async (value) => {
      this.plugin.settings.showHiddenFiles = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Vim Integration" });
    new import_obsidian4.Setting(containerEl).setName("Enable custom vim commands").setDesc("Add directory-specific vim commands and keybindings").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableCustomVimCommands).onChange(async (value) => {
      this.plugin.settings.enableCustomVimCommands = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Performance" });
    new import_obsidian4.Setting(containerEl).setName("Lazy load threshold").setDesc("Number of files before switching to lazy loading").addSlider((slider) => slider.setLimits(100, 5e3, 100).setValue(this.plugin.settings.lazyLoadThreshold).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.lazyLoadThreshold = value;
      await this.plugin.saveSettings();
    }));
    const loggingHeader = containerEl.createEl("h3", { text: "Logging" });
    console.log("Sugar Rush: Creating logging settings section", {
      headerCreated: !!loggingHeader,
      settingsExists: !!this.plugin.settings,
      loggingExists: !!((_a = this.plugin.settings) == null ? void 0 : _a.logging),
      logLevel: (_c = (_b = this.plugin.settings) == null ? void 0 : _b.logging) == null ? void 0 : _c.logLevel
    });
    try {
      new import_obsidian4.Setting(containerEl).setName("Log level").setDesc("Minimum level of logs to record").addDropdown((dropdown) => {
        var _a2, _b2;
        return dropdown.addOption(0 /* TRACE */.toString(), "Trace (Very verbose)").addOption(1 /* DEBUG */.toString(), "Debug (Verbose)").addOption(2 /* INFO */.toString(), "Info (Normal)").addOption(3 /* WARN */.toString(), "Warning (Important)").addOption(4 /* ERROR */.toString(), "Error (Critical)").addOption(5 /* FATAL */.toString(), "Fatal (Critical)").addOption(6 /* OFF */.toString(), "Off (Disabled)").setValue(((_b2 = (_a2 = this.plugin.settings.logging) == null ? void 0 : _a2.logLevel) != null ? _b2 : 2 /* INFO */).toString()).onChange(async (value) => {
          this.plugin.settings.logging.logLevel = parseInt(value);
          await this.plugin.saveSettings();
        });
      });
    } catch (error) {
      console.error("Sugar Rush: Error creating log level setting:", error);
      containerEl.createEl("p", { text: "Error loading logging settings. Check console for details." });
    }
    new import_obsidian4.Setting(containerEl).setName("Enable console logging").setDesc("Log messages to the browser console").addToggle((toggle) => {
      var _a2, _b2;
      return toggle.setValue((_b2 = (_a2 = this.plugin.settings.logging) == null ? void 0 : _a2.enableConsoleLogging) != null ? _b2 : true).onChange(async (value) => {
        if (!this.plugin.settings.logging) {
          this.plugin.settings.logging = Object.assign({}, DEFAULT_SETTINGS.logging);
        }
        this.plugin.settings.logging.enableConsoleLogging = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Enable file logging").setDesc("Save log messages to a file in your vault").addToggle((toggle) => toggle.setValue(this.plugin.settings.logging.enableFileLogging).onChange(async (value) => {
      this.plugin.settings.logging.enableFileLogging = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Log file path").setDesc("Path where log files will be stored").addText((text) => text.setPlaceholder("sugar-rush.log").setValue(this.plugin.settings.logging.logFilePath).onChange(async (value) => {
      this.plugin.settings.logging.logFilePath = value || "sugar-rush.log";
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Max log file size (MB)").setDesc("Maximum size before log files are rotated").addSlider((slider) => slider.setLimits(1, 100, 1).setValue(this.plugin.settings.logging.maxLogFileSize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.logging.maxLogFileSize = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Max log files").setDesc("Number of rotated log files to keep").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.logging.maxLogFiles).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.logging.maxLogFiles = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Include stack traces").setDesc("Include stack traces in error logs").addToggle((toggle) => toggle.setValue(this.plugin.settings.logging.includeStackTrace).onChange(async (value) => {
      this.plugin.settings.logging.includeStackTrace = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName("Timestamp format").setDesc("Format for timestamps in log messages").addDropdown((dropdown) => dropdown.addOption("iso", "ISO 8601 (2023-12-25T10:30:00.000Z)").addOption("locale", "Locale format (12/25/2023, 10:30:00 AM)").addOption("unix", "Unix timestamp (1703504200000)").setValue(this.plugin.settings.logging.timestampFormat).onChange(async (value) => {
      this.plugin.settings.logging.timestampFormat = value;
      await this.plugin.saveSettings();
    }));
    const logManagementDiv = containerEl.createDiv();
    logManagementDiv.createEl("h4", { text: "Log Management" });
    new import_obsidian4.Setting(logManagementDiv).setName("Clear log file").setDesc("Remove all content from the current log file").addButton((button) => button.setButtonText("Clear logs").setCta().onClick(async () => {
      if (this.plugin.logger) {
        await this.plugin.logger.clearLogFile();
      }
    }));
    new import_obsidian4.Setting(logManagementDiv).setName("View log file").setDesc("Open the current log file in Obsidian").addButton((button) => button.setButtonText("Open log file").onClick(async () => {
      const logFile = this.app.vault.getAbstractFileByPath(this.plugin.settings.logging.logFilePath);
      if (logFile instanceof import_obsidian4.TFile) {
        const leaf = this.app.workspace.getLeaf();
        await leaf.openFile(logFile);
      } else {
        new import_obsidian4.Notice("Log file not found. Enable file logging first.");
      }
    }));
    if (this.plugin.logger) {
      this.plugin.logger.getLogFileSize().then((size) => {
        const sizeInMB = (size / (1024 * 1024)).toFixed(2);
        const statusDiv = logManagementDiv.createDiv();
        statusDiv.createEl("small", {
          text: `Current log file size: ${sizeInMB} MB`,
          cls: "setting-item-description"
        });
      });
    }
  }
};
